#!/bin/bash
source .env
case $1 in
    start)
        mkdir -p cozycast-server/cache/avatar
        cd docker-compose
        grep -oE "[^ ]+=" ../.env | sed 's/=//' | xargs -I{} bash -c "echo {}=\${}" > .env
        sudo docker-compose -p cozycast -f docker-compose.yml up -d
        sudo docker exec -it cozycast_coturn_1 \
            turnadmin -a -u kurento -p $KURENTO_PASSWORD -r kurento.org
        exit;
        ;;
    stop)
        cd docker-compose
        sudo docker-compose -p cozycast -f docker-compose.yml down
        exit;
        ;;
    build)
        cd docker-compose
        sudo docker-compose -p cozycast -f docker-compose.yml build
        exit;
        ;;
    dev)
        mkdir -p cozycast-server/cache/avatar
        cd docker-compose
        grep -oE "[^ ]+=" ../.env | sed 's/=//' | xargs -I{} bash -c "echo {}=\${}" > .env
        echo "SOURCE_URL=$(git remote get-url origin)" >> .env
        sudo docker-compose -p cozycast -f docker-compose.yml -f docker-compose.dev.yml up -d
        sudo docker exec -it cozycast_coturn_1 \
            turnadmin -a -u kurento -p $KURENTO_PASSWORD -r kurento.org
        exit;
        ;;
    *)
        printf "Usage: %s: <start|stop|builds>\n" $0
        exit 2
        ;;
esac
