#!/bin/bash
source .env

function setup_env {
    mkdir -p data
    FILE=/etc/resolv.conf
    if [ -f "data/TURN_SECRET" ]; then
        export TURN_SECRET=$(cat data/TURN_SECRET)
    else
        export TURN_SECRET=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 128 | head -n 1)
        echo $TURN_SECRET > data/TURN_SECRET
    fi

    export KURENTO_USERNAME=2139323074:kurento
    export KURENTO_PASSWORD=$(echo -n "$KURENTO_USERNAME" | openssl dgst -sha1 -hmac "$TURN_SECRET" -binary | base64)
    sudo docker network create cozycast_cozycast
    export KURENTO_IP=$(sudo docker network inspect cozycast_cozycast --format="{{(index (index .).IPAM.Config 0).Gateway}}")

    if [ -f "data/COZYCAST_JWT_SECRET" ]; then
        export COZYCAST_JWT_SECRET=$(cat data/COZYCAST_JWT_SECRET)
    else
        export COZYCAST_JWT_SECRET=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 256 | head -n 1)
        echo $COZYCAST_JWT_SECRET > data/COZYCAST_JWT_SECRET
    fi

    if [ -f "data/COZYCAST_DB_PASS" ]; then
        export COZYCAST_DB_PASS=$(cat data/COZYCAST_DB_PASS)
    else
        export COZYCAST_DB_PASS=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)
        echo $COZYCAST_DB_PASS > data/COZYCAST_DB_PASS
    fi

    if [ -f "data/COZYCAST_INIT_ADMIN_PASSWORD" ]; then
        export COZYCAST_INIT_ADMIN_PASSWORD=$(cat data/COZYCAST_INIT_ADMIN_PASSWORD)
    else
        export COZYCAST_INIT_ADMIN_PASSWORD=$(cat /dev/urandom | tr -dc 'a-zA-Z0-9' | fold -w 64 | head -n 1)
        echo $COZYCAST_INIT_ADMIN_PASSWORD > data/COZYCAST_INIT_ADMIN_PASSWORD
    fi

    export COMPOSE_COMPATIBILITY=true
}
setup_env

function coturn_add_kurento_user {
    sudo -E docker exec -it cozycast_coturn_1 \
        turnadmin -a -u kurento -p $KURENTO_PASSWORD -r kurento.org
}

function liquibase_update {
    sudo docker run --rm -it \
        -v $(readlink -f ../liquibase/changelog.xml):/changelog.xml \
        -v $(readlink -f ../liquibase/driver):/liquibase/jdbc \
        --network cozycast_cozycast \
        liquibase/liquibase:3.10.x \
        --driver=org.postgresql.Driver \
        --classpath=/liquibase/jdbc/postgresql-42.2.9.jre7.jar \
        --url="jdbc:postgresql://$COZYCAST_DB_HOST:5432/cozycast" \
        --changeLogFile=/changelog.xml \
        --username=cozycast \
        --password=$COZYCAST_DB_PASS \
        update
}

case $1 in
    start)
        mkdir -p cozycast-server/cache/avatar
        cd docker-compose
        sudo -E docker-compose -p cozycast -f docker-compose.yml up -d
        coturn_add_kurento_user
        liquibase_update
        exit;
        ;;
    stop)
        cd docker-compose
        sudo -E docker-compose -p cozycast -f docker-compose.yml down
        exit;
        ;;
    connect)
        cd docker-compose
        sudo -E docker-compose -p cozycast_2 -f docker-compose.yml -f docker-compose.dev.yml -f docker-compose.connect.yml up -d cozycast-worker
        exit;
        ;;
    build)
        cd docker-compose
        sudo -E docker-compose -p cozycast -f docker-compose.yml build
        exit;
        ;;
    dev)
        mkdir -p cozycast-server/cache/avatar
        cd docker-compose
        export SOURCE_URL=$(git remote get-url origin)
        sudo -E docker-compose -p cozycast -f docker-compose.yml -f docker-compose.dev.yml up -d
        coturn_add_kurento_user
        liquibase_update
        exit;
        ;;
    db)
        sudo docker exec -it cozycast_postgres_1 psql -U cozycast
        exit;
        ;;
    ssl)
        case $2 in
            certbot)
                sudo -E docker run --rm -it -v $(realpath data/certbot2):/etc/letsencrypt/ certbot/certbot \
                    --server https://acme-staging-v02.api.letsencrypt.org/directory -d $DUCKDNS_DOMAIN --manual --preferred-challenges dns-01 certonly
                exit;
                ;;
            renew)
                # --force-renewal
                RELOAD_TRIGGER=./data/certbot/RELOAD
                sudo rm -rf $RELOAD_TRIGGER
                sudo -E docker run --rm -i \
                    -v $(realpath data/certbot):/etc/letsencrypt/  \
                    -v $(realpath cozycast):/cozycast \
                    -v $(realpath .env):/opt/certbot/.env \
                    cozycast-certbot \
                    renew --server https://acme-v02.api.letsencrypt.org/directory \
                        --preferred-challenges dns-01 \
                        --manual-auth-hook="sh /cozycast ssl duckdns \$CERTBOT_VALIDATION" \
                        --manual-cleanup-hook="sh /cozycast ssl duckdns clear \$CERTBOT_VALIDATION" \
                        --deploy-hook "touch /etc/letsencrypt/RELOAD"

                if test -f "$RELOAD_TRIGGER"; then
                    echo "$RELOAD_TRIGGER exists."
                    ./cozycast ssl keystore
                    echo "sudo docker restart cozycast_cozycast-server_1"
                    sudo rm -rf $RELOAD_TRIGGER
                fi
                exit
                ;;
            duckdns)
                if [ "$3" == "clear" ]; then
                    TXT_SECRET=$4
                    curl "https://www.duckdns.org/update?domains=$DUCKDNS_DOMAIN&token=$DUCKDNS_TOKEN&txt=$TXT_SECRET&clear=true"
                else
                    TXT_SECRET=$3
                    curl "https://www.duckdns.org/update?domains=$DUCKDNS_DOMAIN&token=$DUCKDNS_TOKEN&txt=$TXT_SECRET"
                fi
                sleep 60
                exit;
                ;;
            keystore)
                DIRECTORY=$(sudo -E realpath data/certbot/live/$DUCKDNS_DOMAIN)
                echo $DIRECTORY
                if test -z "$CHAIN_FILE"; then
                    CA_FILE="chain.pem"
                fi
                sudo -E openssl pkcs12 -export \
                         -in $DIRECTORY/cert.pem \
                         -inkey $DIRECTORY/privkey.pem \
                         -out $DIRECTORY/server.p12 \
                         -CAfile $DIRECTORY/$CHAIN_FILE -chain \
                         -name $DUCKDNS_DOMAIN \
                         -passout 'env:KEYSTORE_PASSWORD'
                exit;
                ;;
            *)
                printf "Usage: $0 $1: <certbot|duckdns|keystore|reload>\n"
                printf "\n"
                printf "    certbot   Request certificate via certbot\n"
                printf "    duckdns   Update TXT record of duckdns domain \n"
                printf "    keystore  Convert certificate to .p12 keystore \n"
                exit 2
                ;;
        esac
        ;;
    gvisor)
        (
          set -e
          URL=https://storage.googleapis.com/gvisor/releases/master/latest
          wget ${URL}/runsc
          wget ${URL}/runsc.sha512
          sha512sum -c runsc.sha512
          rm -f runsc.sha512
          sudo mv runsc /usr/local/bin
          sudo chown root:root /usr/local/bin/runsc
          sudo chmod 0755 /usr/local/bin/runsc
          sudo cp docker-compose/gvisor.json /etc/docker/daemon.json
          sudo chmod 644 /etc/docker/daemon.json
          sudo chown root:root /etc/docker/daemon.json
        )
        ;;
    *)
        printf "Usage: %s: <start|stop|build|dev|db>\n" $0
        printf "\n"
        printf "    start   Starts cozycast containers with the latest docker image\n"
        printf "    stop    Stops all cozycast containers\n"
        printf "    build   Builds all cozycast docker images\n"
        printf "    dev     Start cozycast in live edit mode\n"
        printf "    db      Connect to postgres via psql\n"
        exit 2
        ;;
esac
