#!/bin/bash
source .env
case $1 in
    start)
        mkdir -p cozycast-server/cache/avatar
        cd docker-compose
        rm .env 2> /dev/null
        echo "TURN_SECRET=$TURN_SECRET" >> .env
        echo "PUBLIC_IP=$PUBLIC_IP" >> .env
        echo "PRIVATE_IP=$PRIVATE_IP" >> .env
        echo "TURN_IP=$TURN_IP" >> .env
        echo "KURENTO_IP=$KURENTO_IP" >> .env
        echo "COZYCAST_IP=$COZYCAST_IP" >> .env
        echo "KURENTO_USERNAME=$KURENTO_USERNAME" >> .env
        echo "KURENTO_PASSWORD=$KURENTO_PASSWORD" >> .env
        echo "SOURCE_URL=$SOURCE_URL" >> .env

        sudo docker-compose -f docker-compose.yml up -d
        sudo docker exec -it docker-compose_coturn_1 \
            turnadmin -a -u kurento -p $KURENTO_PASSWORD -r kurento.org
        exit;
        ;;
    stop)
        cd docker-compose
        sudo docker-compose -f docker-compose.yml down
        exit;
        ;;
    build)
        cd docker-compose
        sudo docker-compose -f docker-compose.yml build
        exit;
        ;;
    *)
        printf "Usage: %s: <start|stop|builds>\n" $0
        exit 2
        ;;
esac
