micronaut:
    application:
        name: cozycast-server
    server:
        port: 80
        multipart:
          maxFileSize: 5MB
        netty:
            responses:
                file:
                    cache-seconds: 604800
    router:
        static-resources:
            default:
                enabled: true
                mapping: "/**"
                paths: "classpath:static"
    io:
        watch:
            paths: src/main
            restart: true
    security:
        enabled: true
        endpoints:
            login:
                enabled: true
            oauth:
                enabled: true
        authentication: bearer
        token:
            jwt:
                generator:
                    access-token:
                        expiration: 3600
                    refresh-token:
                        secret: ${COZYCAST_JWT_SECRET}
                enabled: true
                signatures:
                    secret:
                        generator:
                            secret: ${COZYCAST_JWT_SECRET}
                            jws-algorithm: HS256
        intercept-url-map:
            -
                pattern: /**
                http-method: GET
                access:
                    - isAnonymous()
grails:
    gorm:
        failOnError: true
dataSource:
    pooled: true
    dbCreate: none
    logSql: true
    url: jdbc:postgresql://${COZYCAST_DB_HOST}:5432/cozycast
    driverClassName: org.postgresql.Driver
    username: cozycast
    password: ${COZYCAST_DB_PASS}
