micronaut:
    application:
        name: cozycast-server
    server:
        port: 80
        multipart:
          maxFileSize: 5MB
    router:
        static-resources:
            default:
                enabled: true
                mapping: "/**"
                paths: "classpath:static"
    io:
        watch:
            paths: src/main
            restart: true
grails:
    gorm:
        failOnError: true
dataSource:
    pooled: true
    dbCreate: none
    url: jdbc:postgresql://${COZYCAST_DB_HOST}:5432/cozycast
    driverClassName: org.postgresql.Driver
    username: cozycast
    password: ${COZYCAST_DB_PASS}
